project:
  type: website
  output-dir: docs

website:
  title: "Calvin Pang"
  navbar:
    title: false
    background: "primary"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Events"
        href: events.qmd
    tools:
      - icon: send
        href: mailto:hello@calvinpang.net
      - icon: github
        href: https://github.com/calvpang
      - icon: linkedin
        href: https://www.linkedin.com/in/calv-pang/
  back-to-top-navigation: true
  page-footer: "Copyright 2024, Calvin Pang"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



